Ft help center #147010569
andela/claymore-healthchecks pull request #13
Opened 2017-07-11 14:47 UTC by bmwachajr

**What does this PR do?**
THis Pull request adds a help center with a FAQ that will ease a users process of getting onboard and help answer some common questions that may arise.

**Description of task completed?**
GIVEN I am a new user to the platform and I am interested in getting onboard
WHEN I look for the documentation on the site concerning how to start and find my way on the platform
THEN I should find a myriad of tutorials, help videos, live chat, FAQ's etc that will ease my process of getting onboard and help answer some common questions that may arise.

**What is the relevant pivotal tracker stories?**
pivotal [](https://www.pivotaltracker.com/story/show/147010569)

<img width="1440" alt="screen shot 2017-07-11 at 17 35 09" src="https://user-images.githubusercontent.com/3606411/28074247-c22e1888-6660-11e7-982c-dada45e338f1.png">
<img width="1440" alt="screen shot 2017-07-11 at 17 35 21" src="https://user-images.githubusercontent.com/3606411/28074248-c231dcf2-6660-11e7-9cc9-a112eeaddac2.png">

2017-07-12 12:33 UTC, DomieBett commented on hc/api/models.py
> +    #use
What is this comment for??

2017-07-12 12:33 UTC, andela-landia requested changes
Add .idea folder to gitignore
Remove all git conflict heads ; clean up your code

2017-07-12 12:33 UTC, andela-landia commented on .gitignore
> +<<<<<<< HEAD
remove git conflict heads

2017-07-12 12:33 UTC, andela-landia commented on .gitignore
> +>>>>>>> develop
remove git conflict marks

2017-07-12 12:33 UTC, andela-landia commented on .idea/claymore-healthchecks.iml
> +<?xml version="1.0" encoding="UTF-8"?>
add  this file to gitignore

2017-07-12 12:33 UTC, andela-landia commented on hc/accounts/tests/test_profile.py
> +<<<<<<< HEAD
remove conflict heads

2017-07-12 12:33 UTC, andela-landia commented on hc/accounts/tests/test_switch_team.py
> +<<<<<<< HEAD
remove git confict errors

2017-07-12 12:34 UTC, DomieBett commented on hc/api/models.py
> +            ###que wtf
And this?

2017-07-17 09:13 UTC, bmwachajr commented on .idea/claymore-healthchecks.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Added to git ignore

2017-07-17 12:28 UTC, andela-landia reviewed
Remove the .idea folder from github using `git rm `

2017-07-17 12:40 UTC, merged