Ft front tests #147010553
andela/claymore-healthchecks pull request #2
Opened 2017-06-27 07:29 UTC by DomieBett

2017-06-27 12:05 UTC, Farhanisto commented on hc/front/tests/test_add_channel.py
> -    ### Test that the team access works
This should go after method definition

2017-06-27 12:06 UTC, andela-landia requested changes
Check out the questions and comments

2017-06-27 12:06 UTC, andela-landia commented on hc/front/tests/test_add_channel.py
> +        self.assertEqual(intergration.status_code, 404)
Why remove this "Bad kind test"?

2017-06-27 12:06 UTC, andela-landia commented on hc/front/tests/test_add_channel.py
> -    ### Test that the team access works
Why did you remove this comments yet they describe the tests you wrote?

2017-06-27 12:06 UTC, andela-landia commented on hc/front/tests/test_add_check.py
> +        self.client.post(url)
Why do a post yet no data is being passed to the url consider a GET

2017-06-27 12:06 UTC, andela-landia commented on hc/front/tests/test_add_pushbover.py
> +        self.client.login(username="alice@example.org", password="password")
Thought login generates a session already elaborate on the session below

2017-06-27 12:09 UTC, andela-landia commented on hc/front/tests/test_add_channel.py
> -    ### Test that the team access works
i agree

2017-06-27 12:10 UTC, andela-landia commented on hc/front/tests/test_add_pushbover.py
> +        assert r.status_code == 400
instead of asserting just the status code, assert body contents too

2017-06-27 12:12 UTC, andela-landia commented on hc/front/tests/test_add_channel.py
> +        self.assertEqual(integration.status_code, 400)
Assert body content too

2017-06-27 12:15 UTC, andela-landia commented on hc/front/tests/test_add_pushbover.py
> +        r = self.client.get("/integrations/add_pushover/?%s" % params)
Use `format ` instead of `%s` ("/integrations/add_pushover/?{}".format(params))

2017-06-27 12:22 UTC, Bryoo commented on hc/front/tests/test_add_channel.py
> +    def test_team_access_works(self):
add comment on what test does

2017-06-27 12:22 UTC, Bryoo commented on hc/front/tests/test_add_check.py
> +        check = Check.objects.filter()
why use .filter() when there's nothing specific you're filtering? What of .all()?

2017-06-27 12:24 UTC, bmwachajr commented on hc/front/tests/test_add_check.py
> +        check_code = list(check)[0].code
Why did you convert check into a list ? 
Is check a tuple ? 
if so, whats the problem of accessing the  check[0].code values for the tuple

2017-06-27 12:24 UTC, bmwachajr commented on hc/front/tests/test_add_pushbover.py
> +    def test_it_validates_priority(self):
Couldnt **test_pushover_validates_priority** be a more descriptive method name ?

2017-06-27 12:24 UTC, bmwachajr commented on .gitignore
> +hc-env
you have 2 virtual environments ?

2017-06-27 12:30 UTC, Bryoo commented on hc/front/tests/test_add_pushbover.py
> +        r = self.client.get("/integrations/add_pushover/?%s" % params)
have a descriptive variable name. i.e. response

2017-06-27 20:14 UTC, andela-landia reviewed
Your commit message is not an Edit but rather one of Fix, Feature, Chore

2017-06-27 20:21 UTC, DomieBett commented
So how would i label the last two commits, one which deletes folder and one which adds item to .gitignore...?

2017-06-27 20:22 UTC, andela-landia reviewed
[FIx #467439829]------

2017-06-27 20:30 UTC, DomieBett commented
Python and Github conventions are going to be the end of me...haha. Will try to adhere to that ...thanks and goodnight...

2017-06-28 12:04 UTC, andela-landia approved these changes

2017-06-28 12:05 UTC, merged