Feature fix accounts tests
andela/claymore-healthchecks pull request #3
Opened 2017-06-27 15:22 UTC by bmwachajr

2017-06-28 12:26 UTC, DomieBett commented on hc/accounts/tests/test_profile.py
> +        #print(len(mail.outbox))
This commented out line is not needed.

2017-06-28 12:29 UTC, andela-landia reviewed
Add all local files to your gitignore. and delete them from github using `git rm`

2017-06-28 12:29 UTC, andela-landia commented on hc/accounts/tests/test_profile.py
> +        #print(len(mail.outbox))
Remove commented code

2017-06-28 12:29 UTC, andela-landia commented on hc/accounts/tests/test_profile.py
> +        self.assertTrue("Here's a link to set a password for your account on healthchecks.io:" in email.body)
👍

2017-06-28 12:29 UTC, andela-landia commented on hc/local_settings_old.py
> +#Database configuration
Add this file to your gitignore as they are your personal settings

2017-06-28 12:33 UTC, Bryoo commented on hc/local_settings_old.py
> +#Database configuration
is this file really necessary? Should be in git ignore

2017-06-28 12:36 UTC, Bryoo commented on local_settings.py
> +"""
this file should be in gitignore

2017-06-29 10:14 UTC, andela-landia commented
@bmwachajr Resolve the conflicts above

2017-07-03 10:06 UTC, andela-landia requested changes
Remove the local files from github

2017-07-03 10:13 UTC, andela-landia approved these changes

2017-07-03 10:14 UTC, merged