Ft new dashboard tab #147010557
andela/claymore-healthchecks pull request #6
Opened 2017-07-03 12:04 UTC by bmwachajr

**What does this PR do?**
A User requires a new dashboard tab for unresolved stuff

**Description of Task completed** 
GIVEN that a user has been notified of a failed job
WHEN the user logs into the dashboard
THEN they should have a view listing all their failed jobs which they have been notified about.

**What are the relevant pivotal tracker stories?** 
[Pivotal Tracker](https://www.pivotaltracker.com/story/show/147010557)

2017-07-03 12:23 UTC, 8318 commented on templates/front/my_failed_checks_mobile.html
> +    <p>You donot have any failing checks</p>
ensure you don't have misspellings within your code

2017-07-03 12:27 UTC, margaretkinyanjui reviewed
..

2017-07-03 12:45 UTC, andela-landia requested changes
implement madge's PR

2017-07-10 11:50 UTC, andela-landia approved these changes

2017-07-10 11:50 UTC, merged