Add more time to grace and period
andela/claymore-healthchecks pull request #9
Opened 2017-07-05 16:21 UTC by Bryoo

What does this PR do?
User should be able to set timeouts and grace values for days exceeding 30

Description of Task completed
This period should be extended because it is possible to have cron jobs that run once every 30+ days

What are the relevant pivotal tracker stories?
[Pivotal Tracker](https://www.pivotaltracker.com/story/show/147010559)

2017-07-07 07:31 UTC, bmwachajr commented on static/js/checks.js
> +    var MINUTE = {name: "min", nsecs: 60};
It would be better to maintain the key as minute because min could mean minimum

2017-07-10 08:42 UTC, Bryoo commented on static/js/checks.js
> +    var MINUTE = {name: "min", nsecs: 60};
cool

2017-07-10 08:42 UTC, Bryoo commented on static/js/checks.js
> +    var MINUTE = {name: "min", nsecs: 60};
Oh, minute was taking up too much space, that's why i did that

2017-07-10 08:43 UTC, Bryoo commented on static/js/checks.js
> +    var MINUTE = {name: "min", nsecs: 60};
on the front end that is. When adding the grace period n stuff

2017-07-12 12:27 UTC, andela-landia requested changes

2017-07-12 12:27 UTC, andela-landia commented on static/js/checks.js
> +            'max': [5184000, 5184000]
think max should be one number not an array

2017-07-12 12:27 UTC, andela-landia commented on static/js/checks.js
> +            values: [60, 1800, 3600, 43200, 86400, 604800, 2592000, 5184000],
this should match all values in your range include 3456000, 4320000

2017-07-17 08:37 UTC, Bryoo commented on static/js/checks.js
> +            'max': [5184000, 5184000]
fixed

2017-07-17 08:38 UTC, Bryoo commented on static/js/checks.js
> +            values: [60, 1800, 3600, 43200, 86400, 604800, 2592000, 5184000],
Making them really messes up the slider.

2017-07-17 13:06 UTC, andela-landia approved these changes

2017-07-17 13:06 UTC, merged